'use client'
import { useEffect, useMemo, useRef, useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, BookOpen, Headphones, Heart, Radio, Users } from 'lucide-react'
import { useAuth } from '@/components/providers/AuthProvider'
import { INTENTS, resolveFirstStep, resolveHeroGreeting, type HomeIntent, type LiveState } from '@/lib/home/contextual'
import { resolveMemberNextAction, type MemberNextAction } from '@/lib/member-home/next-action'
import { track } from '@/lib/analytics'

const dateLabel = (v?: string) => v ? new Intl.DateTimeFormat('fr-FR', { weekday: 'long', day: 'numeric', month: 'long', hour: '2-digit', minute: '2-digit' }).format(new Date(v)) : 'Préparé pour le prochain direct'

export function ContextualHome({ liveState }: { liveState: LiveState }) {
  const { user, profile, isDemo } = useAuth()
  const authenticated = Boolean(user) && !isDemo
  const firstName = authenticated ? (profile?.prenom || profile?.first_name || '') : ''
  const hero = resolveHeroGreeting({ authenticated, firstName })
  const [intent, setIntent] = useState<HomeIntent | null>(null)
  const [memberNextAction, setMemberNextAction] = useState<MemberNextAction | null>(null)
  const revealRef = useRef<HTMLDivElement>(null)
  useEffect(() => { if (!authenticated) return; let cancelled = false; (async () => { try { const [f, i] = await Promise.all([fetch('/api/member/formations', { credentials: 'same-origin' }).then(r => r.ok ? r.json() : null), fetch('/api/member/integration-progression', { credentials: 'same-origin' }).then(r => r.ok ? r.json() : null)]); if (!cancelled) setMemberNextAction(resolveMemberNextAction({ integration: i?.ok ? i.data : null, formations: f?.ok ? f.data?.inscriptions || [] : [] })) } catch { if (!cancelled) setMemberNextAction(null) } })(); return () => { cancelled = true } }, [authenticated])
  useEffect(() => { const root = revealRef.current; if (!root) return; const io = typeof IntersectionObserver === 'undefined' ? null : new IntersectionObserver(es => es.forEach(e => e.isIntersecting && (e.target.classList.add('is-visible'), io?.unobserve(e.target))), { threshold: .12 }); root.querySelectorAll('section').forEach(el => { el.classList.add('home-reveal'); io?.observe(el) }); return () => io?.disconnect() }, [])
  const firstStep = useMemo(() => resolveFirstStep({ intent: intent || 'grow_in_faith', authenticated, memberNextAction, liveState }), [intent, authenticated, memberNextAction, liveState])
  const primaryHref = authenticated ? (memberNextAction?.href || '/member/dashboard') : '/rejoindre'
  const selectIntent = (id: HomeIntent) => { setIntent(id); track('home_intent_selected', { intent: id }) }
  return <div ref={revealRef} className="bg-charbon text-pearl overflow-hidden">
    <section className="relative min-h-[min(720px,90svh)] flex items-center overflow-hidden" aria-labelledby="contextual-hero-title"><Image src="/images/prayers/prayer-consecration.jpg" alt="Un moment de prière" fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(5,7,16,.54),rgba(5,6,12,.64)_48%,#06060a_100%)]" /><div className="relative z-10 container-cinematic max-w-5xl pt-28 pb-20"><p className="font-inter text-[11px] uppercase tracking-[.28em] text-[#F5E6A7]/75 mb-5">Citadelle · La maison qui t’accompagne</p><h1 id="contextual-hero-title" className="font-cinzel font-black text-4xl sm:text-5xl md:text-7xl leading-[1.05] max-w-3xl text-white">{hero.title}</h1><p className="font-cormorant text-2xl md:text-3xl text-[#F5E6A7] mt-5 max-w-2xl">{hero.subtitle}</p><p className="font-inter text-sm md:text-base leading-relaxed text-white/65 max-w-xl mt-5">Enseignements, parcours, prières, directs et accompagnement réunis dans un même espace pour avancer avec Dieu.</p>{liveState.status !== 'OFFLINE' && <div className="mt-8 max-w-xl rounded-2xl border border-[#D4AF37]/25 bg-black/35 backdrop-blur-md p-4"><div className="flex items-start gap-3"><Radio className={`w-5 h-5 mt-0.5 ${liveState.status === 'LIVE' ? 'text-red-400' : 'text-[#D4AF37]'}`} /><div><p className="font-inter text-[10px] uppercase tracking-[.22em] font-bold text-[#D4AF37]">{liveState.status === 'LIVE' ? 'En direct maintenant' : 'Prochain direct'}</p><p className="font-cinzel text-white font-bold mt-1">{liveState.title}</p>{liveState.status === 'UPCOMING' && <p className="font-inter text-xs text-white/55 mt-1">{dateLabel(liveState.scheduledAt)}</p>}</div></div></div>}<div className="flex flex-col sm:flex-row gap-3 mt-8"><Link href={primaryHref} className="btn-gold-cinematic inline-flex items-center justify-center gap-2 min-h-[50px] px-6">{authenticated ? 'ENTRER DANS MA CITADELLE' : 'COMMENCER MAINTENANT'}<ArrowRight className="w-4 h-4" /></Link>{!authenticated && <Link href="#intentions" className="inline-flex items-center justify-center min-h-[50px] px-5 rounded-full border border-white/20 text-white/65 text-sm">Découvrir Citadelle</Link>}</div></div></section>
    <section id="intentions" className="container-cinematic max-w-5xl py-16 md:py-20" aria-labelledby="intentions-title"><p className="font-inter text-[10px] uppercase tracking-[.25em] text-[#D4AF37]/75 mb-3">Un point de départ simple</p><h2 id="intentions-title" className="font-cinzel text-3xl md:text-4xl text-white">De quoi as-tu besoin aujourd’hui ?</h2><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-8">{INTENTS.map(item => <button key={item.id} type="button" onClick={() => selectIntent(item.id)} className="text-left p-5 rounded-2xl border border-white/10 bg-white/[.03]"><span className="font-cinzel text-white font-bold">{item.title}</span><span className="block font-inter text-xs text-white/45 mt-2">{item.description}</span></button>)}</div><div className="mt-8 rounded-2xl border border-[#D4AF37]/25 bg-[#D4AF37]/[.06] p-5 md:p-7"><p className="font-inter text-[10px] uppercase tracking-[.24em] text-[#D4AF37]">{intent ? 'Ton premier pas' : 'Ton premier pas peut commencer ici'}</p><h3 className="font-cinzel text-xl md:text-2xl text-white mt-2">{firstStep.title}</h3><p className="font-inter text-sm text-white/60 mt-2 max-w-xl">{firstStep.reason}</p><Link href={firstStep.href} className="inline-flex items-center gap-2 mt-5 text-sm font-semibold text-[#F5E6A7]">{firstStep.cta}<ArrowRight className="w-4 h-4" /></Link></div></section>
    <section className="border-y border-white/[.06] bg-[#0b0c14]" aria-labelledby="today-title"><div className="container-cinematic max-w-5xl py-16 md:py-20"><p className="font-inter text-[10px] uppercase tracking-[.25em] text-[#D4AF37]/75 mb-3">Ce qui peut t’aider maintenant</p><h2 id="today-title" className="font-cinzel text-3xl text-white mb-7">Aujourd’hui sur Citadelle</h2><div className="grid md:grid-cols-3 gap-4 items-stretch">
      <article className="today-primary-card md:col-span-2 rounded-2xl border border-[#D4AF37]/25 overflow-hidden bg-gradient-to-br from-[#1b1630] to-[#0b0c14]"><div className="today-primary-image"><Image src="/images/formations/parcours-1/parcours-1-je-decouvre-la-maison.png" alt="Je découvre la maison" width={1200} height={675} className="w-full h-auto object-contain" /></div><div className="today-primary-content p-6"><p className="today-card-label">GRANDIR</p><h3 className="font-cinzel text-xl text-white mt-2">Un chemin clair pour avancer</h3><p className="font-inter text-sm text-white/55 mt-2">Parcours, enseignements et prière réunis au même endroit.</p><Link href={primaryHref} className="inline-flex items-center gap-2 mt-5 text-sm font-semibold text-[#F5E6A7]">Ouvrir <ArrowRight className="w-4 h-4" /></Link></div></article>
      <article className="today-support-card rounded-2xl border border-[#D4AF37]/20 overflow-hidden bg-[#171126]"><Image src="/images/podcast/covers/instant-citadelle-cover.png" alt="Podcast Instant Citadelle" width={640} height={360} className="w-full aspect-video object-cover" /><div className="p-5"><p className="today-card-label">ÉCOUTER</p><h3 className="font-cinzel text-lg text-white mt-2">Instant Citadelle</h3><p className="font-inter text-sm text-white/55 mt-2">Un enseignement à écouter aujourd’hui.</p><Link href="/podcast" className="inline-flex items-center gap-2 mt-4 text-sm font-semibold text-[#F5E6A7]">Écouter maintenant <ArrowRight className="w-4 h-4" /></Link></div></article>
      <article className="today-support-card rounded-2xl border border-white/10 overflow-hidden bg-white/[.03]"><Image src="/images/prayers/prayer-family.jpg" alt="Prochain rendez-vous" width={640} height={360} className="w-full aspect-video object-cover" /><div className="p-5"><p className="today-card-label">PARTICIPER</p><h3 className="font-cinzel text-lg text-white mt-2">{liveState.status === 'UPCOMING' ? liveState.title : 'Le prochain rendez-vous'}</h3><p className="font-inter text-sm text-white/55 mt-2">{liveState.status === 'UPCOMING' ? dateLabel(liveState.scheduledAt) : 'Retrouvons-nous pour avancer ensemble.'}</p><Link href="/evenements" className="inline-flex items-center gap-2 mt-4 text-sm font-semibold text-[#F5E6A7]">Voir le rendez-vous <ArrowRight className="w-4 h-4" /></Link></div></article>
      <article className="today-support-card rounded-2xl border border-white/10 overflow-hidden bg-white/[.03]"><div className="p-6"><Heart className="w-5 h-5 text-[#D4AF37]" /><p className="today-card-label mt-5">ÊTRE ACCOMPAGNÉ</p><h3 className="font-cinzel text-lg text-white mt-2">Un espace pour souffler</h3><p className="font-inter text-sm text-white/50 mt-2">Prière, écoute et présence quand tu en as besoin.</p><Link href="/priere" className="inline-flex items-center gap-2 mt-5 text-sm font-semibold text-[#F5E6A7]">Déposer une demande <ArrowRight className="w-4 h-4" /></Link></div></article>
    </div></div></section>
    <section className="container-cinematic max-w-5xl py-16 md:py-20" aria-labelledby="pastoral-title"><div className="rounded-3xl border border-[#D4AF37]/20 bg-gradient-to-br from-[#171126] to-[#0a0a10] p-7 md:p-10 flex flex-col md:flex-row md:items-center md:justify-between gap-7"><div className="max-w-xl"><p className="font-inter text-[10px] uppercase tracking-[.25em] text-[#D4AF37]/75 mb-3">Une présence humaine</p><h2 id="pastoral-title" className="font-cinzel text-3xl text-white">Tu n’as pas besoin de tout porter seul.</h2><p className="font-inter text-sm text-white/60 mt-3">Besoin de prière, d’écoute ou simplement de parler à quelqu’un ?</p></div><div className="flex flex-col gap-3 items-start"><Link href="/priere" className="btn-gold-cinematic inline-flex flex-none min-h-[48px] px-6">Demander une prière</Link><Link href="/contact" className="inline-flex flex-none min-h-[48px] px-6 rounded-full border border-white/20 text-white/75 text-sm">Parler à quelqu’un</Link></div></div></section>
    <section className="relative border-t border-white/[.06]" aria-labelledby="final-home-title"><div className="container-cinematic max-w-4xl py-16 md:py-24 text-center"><h2 id="final-home-title" className="font-cinzel text-3xl md:text-4xl text-[#F5E6A7]">Ton prochain pas peut commencer aujourd’hui.</h2><p className="font-inter text-sm text-white/55 mt-4">Entre dans Citadelle et avance simplement, un pas après l’autre.</p></div></section>
  </div>
}
