'use client'
import { useEffect,useMemo,useRef,useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight,BookOpen,Headphones,Heart,Radio,Users } from 'lucide-react'
import { useAuth } from '@/components/providers/AuthProvider'
import { INTENTS,resolveFirstStep,type HomeIntent,type LiveState } from '@/lib/home/contextual'
import { resolveMemberNextAction,type MemberNextAction } from '@/lib/member-home/next-action'
import { track } from '@/lib/analytics'
const dateLabel=(v?:string)=>v?new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'Préparé pour le prochain direct'
export function ContextualHome({liveState}:{liveState:LiveState}){
 const {user,profile,isDemo}=useAuth(); const authenticated=Boolean(user); const [intent,setIntent]=useState<HomeIntent|null>(null); const [memberNextAction,setMemberNextAction]=useState<MemberNextAction|null>(null)
 useEffect(()=>{if(!authenticated||isDemo)return;let cancelled=false;(async()=>{try{const [f,i]=await Promise.all([fetch('/api/member/formations',{credentials:'same-origin'}).then(r=>r.ok?r.json():null),fetch('/api/member/integration-progression',{credentials:'same-origin'}).then(r=>r.ok?r.json():null)]);if(!cancelled)setMemberNextAction(resolveMemberNextAction({integration:i?.ok?i.data:null,formations:f?.ok?f.data?.inscriptions||[]:[]}))}catch{if(!cancelled)setMemberNextAction(null)}})();return()=>{cancelled=true}},[authenticated,isDemo])
 const firstStep=useMemo(()=>resolveFirstStep({intent:intent||'grow_in_faith',authenticated,memberNextAction,liveState}),[intent,authenticated,memberNextAction,liveState]); const firstName=profile?.prenom||profile?.first_name||''; const primaryHref=authenticated?(memberNextAction?.href||'/member/dashboard'):'/rejoindre'; const primaryLabel=authenticated?(memberNextAction?.ctaLabel==='Continuer'?'CONTINUER MON PARCOURS':'ENTRER DANS MA CITADELLE'):'COMMENCER MAINTENANT'
 const selectIntent=(id:HomeIntent)=>{setIntent(id);track('home_intent_selected',{intent:id})}
 const revealRef=useRef<HTMLDivElement>(null)
 useEffect(()=>{const root=revealRef.current;if(!root)return;root.querySelector('[aria-labelledby="today-title"] a')?.classList.add('home-today-primary');root.querySelector('[aria-labelledby="pastoral-title"] > div')?.classList.add('home-pastoral-panel');if(typeof IntersectionObserver==='undefined')return;const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&(e.target.classList.add('is-visible'),io.unobserve(e.target))),{threshold:.12});root.querySelectorAll('section').forEach(el=>{el.classList.add('home-reveal');io.observe(el)});return()=>io.disconnect()},[])
 return <div ref={revealRef} className="bg-charbon text-pearl overflow-hidden">
  <section className="relative min-h-[min(720px,90svh)] flex items-center overflow-hidden" aria-labelledby="contextual-hero-title"><Image src="/images/prayers/prayer-consecration.jpg" alt="Un moment de prière" fill priority sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(5,7,16,.54),rgba(5,6,12,.64)_48%,#06060a_100%)]"/><div className="relative z-10 container-cinematic max-w-5xl pt-28 pb-20"><p className="font-inter text-[11px] uppercase tracking-[.28em] text-[#F5E6A7]/75 mb-5">Citadelle · La maison qui t’accompagne</p><h1 id="contextual-hero-title" className="font-cinzel font-black text-4xl sm:text-5xl md:text-7xl leading-[1.05] max-w-3xl text-white">{authenticated&&firstName?`Bonjour ${firstName}.`:'N’avance plus seul dans ta foi.'}</h1><p className="font-cormorant text-2xl md:text-3xl text-[#F5E6A7] mt-5 max-w-2xl">{authenticated?'Ton prochain pas peut commencer ici.':'Citadelle t’aide à grandir en Christ, un pas après l’autre.'}</p><p className="font-inter text-sm md:text-base leading-relaxed text-white/65 max-w-xl mt-5">Enseignements, parcours, prières, directs et accompagnement réunis dans un même espace pour avancer avec Dieu.</p>{liveState.status!=='OFFLINE'&&<div className="mt-8 max-w-xl rounded-2xl border border-[#D4AF37]/25 bg-black/35 backdrop-blur-md p-4"><div className="flex items-start gap-3"><Radio className={`w-5 h-5 mt-0.5 ${liveState.status==='LIVE'?'text-red-400':'text-[#D4AF37]'}`} aria-hidden/><div className="min-w-0 flex-1"><p className="font-inter text-[10px] uppercase tracking-[.22em] font-bold text-[#D4AF37]">{liveState.status==='LIVE'?'En direct maintenant':'Prochain direct'}</p><p className="font-cinzel text-white font-bold mt-1 truncate">{liveState.title}</p>{liveState.status==='UPCOMING'&&<p className="font-inter text-xs text-white/55 mt-1">{dateLabel(liveState.scheduledAt)}</p>}{liveState.status==='LIVE'&&<Link href="/live" onClick={()=>track('home_live_clicked')} className="inline-flex items-center gap-2 mt-3 text-sm font-semibold text-[#F5E6A7]">Regarder le direct <ArrowRight className="w-4 h-4"/></Link>}</div></div></div>}<div className="flex flex-col sm:flex-row gap-3 mt-8"><Link href={primaryHref} onClick={()=>track(authenticated?'home_cta_primary_clicked':'home_join_clicked')} className="btn-gold-cinematic inline-flex items-center justify-center gap-2 min-h-[50px] px-6">{primaryLabel}<ArrowRight className="w-4 h-4"/></Link>{!authenticated&&<Link href="#intentions" className="inline-flex items-center justify-center min-h-[50px] px-5 rounded-full border border-white/20 text-white/65 text-sm">Découvrir Citadelle</Link>}</div></div></section>
  <section id="intentions" className="container-cinematic max-w-5xl py-16 md:py-20" aria-labelledby="intentions-title"><p className="font-inter text-[10px] uppercase tracking-[.25em] text-[#D4AF37]/75 mb-3">Un point de départ simple</p><h2 id="intentions-title" className="font-cinzel text-3xl md:text-4xl text-white">De quoi as-tu besoin aujourd’hui ?</h2><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-8">{INTENTS.map(item=><button key={item.id} type="button" onClick={()=>selectIntent(item.id)} className={`text-left p-5 rounded-2xl border transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#D4AF37] ${intent===item.id?'border-[#D4AF37]/60 bg-[#D4AF37]/10':'border-white/10 bg-white/[.03] hover:border-[#D4AF37]/35'}`}><span className="font-cinzel text-white font-bold">{item.title}</span><span className="block font-inter text-xs text-white/45 mt-2">{item.description}</span></button>)}</div><div className="mt-8 rounded-2xl border border-[#D4AF37]/25 bg-[#D4AF37]/[.06] p-5 md:p-7" aria-live="polite"><p className="font-inter text-[10px] uppercase tracking-[.24em] text-[#D4AF37]">{intent?'Ton premier pas':'Ton premier pas peut commencer ici'}</p><h3 className="font-cinzel text-xl md:text-2xl text-white mt-2">{firstStep.title}</h3><p className="font-inter text-sm text-white/60 mt-2 max-w-xl">{firstStep.reason}</p><Link href={firstStep.href} onClick={()=>track('home_first_step_clicked',{intent:intent||'default',type:firstStep.type})} className="inline-flex items-center gap-2 mt-5 text-sm font-semibold text-[#F5E6A7]">{firstStep.cta}<ArrowRight className="w-4 h-4"/></Link></div></section>
  <section className="border-y border-white/[.06] bg-[#0b0c14]" aria-labelledby="today-title"><div className="container-cinematic max-w-5xl py-16 md:py-20"><p className="font-inter text-[10px] uppercase tracking-[.25em] text-[#D4AF37]/75 mb-3">Ce qui peut t’aider maintenant</p><h2 id="today-title" className="font-cinzel text-3xl text-white mb-7">Aujourd’hui sur Citadelle</h2><div className="grid md:grid-cols-3 gap-3"><Link href={liveState.status==='LIVE'?'/live':primaryHref} onClick={()=>track(liveState.status==='LIVE'?'home_live_clicked':'home_today_content_clicked')} className="md:col-span-2 rounded-2xl border border-[#D4AF37]/25 bg-gradient-to-br from-[#1b1630] to-[#0b0c14] p-6 min-h-[190px] flex flex-col justify-between"><div><Radio className="w-5 h-5 text-[#D4AF37]" aria-hidden/><h3 className="font-cinzel text-xl text-white mt-4">{liveState.status==='LIVE'?'Le direct est en cours':authenticated&&memberNextAction?'Continuer là où tu t’es arrêté':'Un chemin clair pour avancer'}</h3><p className="font-inter text-sm text-white/55 mt-2">{liveState.status==='LIVE'?liveState.title:authenticated&&memberNextAction?memberNextAction.reason:'Parcours, enseignements et prière réunis au même endroit.'}</p></div><span className="font-inter text-xs text-[#F5E6A7]">Ouvrir <ArrowRight className="inline w-3.5 h-3.5"/></span></Link><Link href="/priere" onClick={()=>track('home_prayer_clicked')} className="rounded-2xl border border-white/10 bg-white/[.03] p-6 min-h-[190px] flex flex-col justify-between"><Heart className="w-5 h-5 text-[#D4AF37]" aria-hidden/><div><h3 className="font-cinzel text-lg text-white">Un espace pour souffler</h3><p className="font-inter text-sm text-white/50 mt-2">Prière, écoute et présence quand tu en as besoin.</p></div><span className="font-inter text-xs text-[#F5E6A7]">Déposer une demande <ArrowRight className="inline w-3.5 h-3.5"/></span></Link></div><div className="flex flex-wrap gap-4 mt-5 text-xs text-white/50"><Link href="/formations" onClick={()=>track('home_today_content_clicked',{type:'formation'})} className="inline-flex items-center gap-2"><BookOpen className="w-4 h-4 text-[#D4AF37]"/>Formations</Link><Link href="/podcast" onClick={()=>track('home_today_content_clicked',{type:'podcast'})} className="inline-flex items-center gap-2"><Headphones className="w-4 h-4 text-[#D4AF37]"/>Podcast</Link><Link href="/groupes" onClick={()=>track('home_today_content_clicked',{type:'community'})} className="inline-flex items-center gap-2"><Users className="w-4 h-4 text-[#D4AF37]"/>Communauté</Link></div></div></section>
  <section className="container-cinematic max-w-5xl py-16 md:py-20" aria-labelledby="pastoral-title"><div className="rounded-3xl border border-[#D4AF37]/20 bg-gradient-to-br from-[#171126] to-[#0a0a10] p-7 md:p-10 flex flex-col md:flex-row md:items-center md:justify-between gap-7"><div className="max-w-xl"><p className="font-inter text-[10px] uppercase tracking-[.25em] text-[#D4AF37]/75 mb-3">Une présence humaine</p><h2 id="pastoral-title" className="font-cinzel text-3xl text-white">Tu n’as pas besoin de tout porter seul.</h2><p className="font-inter text-sm text-white/60 mt-3">Besoin de prière, d’écoute ou simplement de parler à quelqu’un ?</p></div><div className="flex flex-col sm:flex-row gap-3"><Link href="/priere" onClick={()=>track('home_prayer_clicked')} className="btn-gold-cinematic inline-flex items-center justify-center min-h-[46px] px-5">Demander une prière</Link><Link href="/contact" onClick={()=>track('home_pastoral_contact_clicked')} className="inline-flex items-center justify-center min-h-[46px] px-5 rounded-full border border-white/20 text-white/75 text-sm">Parler à quelqu’un</Link></div></div></section>
  <section className="relative border-t border-white/[.06]" aria-labelledby="final-home-title"><div className="container-cinematic max-w-4xl py-16 md:py-24 text-center"><h2 id="final-home-title" className="font-cinzel text-3xl md:text-4xl text-[#F5E6A7]">Ton prochain pas peut commencer aujourd’hui.</h2><p className="font-inter text-sm text-white/55 mt-4">Entre dans Citadelle et avance simplement, un pas après l’autre.</p><div className="flex flex-col sm:flex-row items-center justify-center gap-3 mt-7"><Link href={authenticated?primaryHref:'/rejoindre'} onClick={()=>track(authenticated?'home_cta_primary_clicked':'home_join_clicked')} className="btn-gold-cinematic inline-flex items-center gap-2 min-h-[50px] px-7">{authenticated?'ENTRER DANS MA CITADELLE':'REJOINDRE CITADELLE'}<ArrowRight className="w-4 h-4"/></Link>{!authenticated&&<Link href="/login" className="text-sm text-white/55 hover:text-[#F5E6A7]">J’ai déjà un compte</Link>}</div></div></section>
 </div>
}
