import 'server-only'
import type { LiveState } from './contextual'
import { refreshAccessToken } from '@/lib/intelligence/connectors/youtube/auth'
import { loadYouTubeConfig } from '@/lib/intelligence/connectors/youtube/config'
type YouTubeItem={id?:string|{videoId?:string};snippet?:{title?:string;publishedAt?:string;scheduledStartTime?:string;thumbnails?:{high?:{url?:string};medium?:{url?:string}}};status?:{lifeCycleStatus?:string;privacyStatus?:string};liveStreamingDetails?:{actualStartTime?:string;scheduledStartTime?:string;actualEndTime?:string}}
type DetectorOptions={now?:Date;fetchImpl?:typeof fetch}
const channelId=()=>process.env.YOUTUBE_CHANNEL_ID?.trim()||'';let cached:{state:LiveState;expiresAt:number}|null=null;let accessToken:{value:string;expiresAtMs:number}|null=null
export function revalidationSeconds(state:LiveState,now=new Date()):number{if(state.status==='LIVE')return 30;if(state.status==='OFFLINE')return 60;if(!state.scheduledAt)return 180;const remaining=Date.parse(state.scheduledAt)-now.getTime();if(remaining<=15*60_000)return 30;if(remaining<=60*60_000)return 180;return 900}
const videoId=(item:YouTubeItem|undefined)=>typeof item?.id==='string'?item.id:item?.id?.videoId
const toState=(item:YouTubeItem|undefined,status:'LIVE'|'UPCOMING'):LiveState|null=>{const id=videoId(item),snippet=item?.snippet,title=snippet?.title?.trim();if(!id||!title||!snippet)return null;const d=item?.liveStreamingDetails,thumbnail=snippet.thumbnails?.high?.url||snippet.thumbnails?.medium?.url;if(status==='LIVE')return{status,title,youtubeVideoId:id,watchUrl:'/live',thumbnail,startedAt:d?.actualStartTime};const scheduledAt=d?.scheduledStartTime||snippet.scheduledStartTime;return{status,title,youtubeVideoId:id,watchUrl:'/live',thumbnail,...(scheduledAt&&Number.isFinite(Date.parse(scheduledAt))?{scheduledAt}:{})}}
const classification=(item:YouTubeItem):'LIVE'|'UPCOMING'|'ENDED'|null=>{const life=item.status?.lifeCycleStatus,privacy=item.status?.privacyStatus,d=item.liveStreamingDetails;if(life==='complete'||d?.actualEndTime)return'ENDED';if(life==='live'||life==='liveStarting'||(d?.actualStartTime&&!d.actualEndTime))return'LIVE';if((privacy==='public'||privacy==='unlisted')&&!d?.actualStartTime&&!d?.actualEndTime&&['ready','created','testStarting','testing'].includes(life||''))return'UPCOMING';return null}
export function classifyOwnedBroadcasts(items:YouTubeItem[],now=new Date()):LiveState|null{const eligible=items.map(item=>({item,kind:classification(item)})).filter((x):x is {item:YouTubeItem;kind:'LIVE'|'UPCOMING'}=>x.kind==='LIVE'||x.kind==='UPCOMING');const live=eligible.find(x=>x.kind==='LIVE');if(live)return toState(live.item,'LIVE');const upcoming=eligible.filter(x=>x.kind==='UPCOMING').sort((a,b)=>{const ad=a.item.liveStreamingDetails?.scheduledStartTime||a.item.snippet?.scheduledStartTime,bd=b.item.liveStreamingDetails?.scheduledStartTime||b.item.snippet?.scheduledStartTime,at=ad?Date.parse(ad):NaN,bt=bd?Date.parse(bd):NaN;if(Number.isFinite(at)&&Number.isFinite(bt))return(at-now.getTime())-(bt-now.getTime());if(Number.isFinite(at))return-1;if(Number.isFinite(bt))return 1;return Date.parse(b.item.snippet?.publishedAt||'')-Date.parse(a.item.snippet?.publishedAt||'')})[0];return upcoming?toState(upcoming.item,'UPCOMING'):null}
async function bearerToken(nowMs:number,fetchImpl:typeof fetch):Promise<string>{const config=loadYouTubeConfig();if(!config)throw new Error('youtube_oauth_not_configured');if(accessToken&&accessToken.expiresAtMs>nowMs+30_000)return accessToken.value;const token=await refreshAccessToken(config,{nowMs,fetchImpl});accessToken={value:token.accessToken,expiresAtMs:token.expiresAtMs};return token.accessToken}
async function ownedBroadcasts(nowMs:number,fetchImpl:typeof fetch):Promise<YouTubeItem[]>{const token=await bearerToken(nowMs,fetchImpl),url=new URL('https://www.googleapis.com/youtube/v3/liveBroadcasts');url.search=new URLSearchParams({part:'id,snippet,status,contentDetails',mine:'true',maxResults:'50'}).toString();const response=await fetchImpl(url,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(!response.ok)throw new Error(`youtube_live_${response.status}`);return(await response.json() as{items?:YouTubeItem[]}).items||[]}
export async function detectYouTubeLive(options:DetectorOptions={}):Promise<LiveState|null>{const now=options.now||new Date(),nowMs=now.getTime(),fetchImpl=options.fetchImpl||fetch;if(!channelId())return null;if(cached&&cached.expiresAt>nowMs)return cached.state.status==='OFFLINE'?null:cached.state;try{const state=classifyOwnedBroadcasts(await ownedBroadcasts(nowMs,fetchImpl),now)||{status:'OFFLINE' as const};cached={state,expiresAt:nowMs+revalidationSeconds(state,now)*1000};return state.status==='OFFLINE'?null:state}catch{return null}}
export function __resetYouTubeLiveCache(){cached=null;accessToken=null}
