import {describe,expect,it,beforeEach,afterEach} from 'vitest'
import {__resetYouTubeLiveCache,detectYouTubeLive,revalidationSeconds} from './youtube-live'
import {resolveLiveState} from './contextual'
const original={key:process.env.YOUTUBE_API_KEY,channel:process.env.YOUTUBE_CHANNEL_ID,clientId:process.env.YOUTUBE_OAUTH_CLIENT_ID,clientSecret:process.env.YOUTUBE_OAUTH_CLIENT_SECRET,refreshToken:process.env.YOUTUBE_OAUTH_REFRESH_TOKEN}
const response=(items:unknown[])=>new Response(JSON.stringify({items,access_token:'access-test',expires_in:3600}),{status:200})
describe('youtube live adaptive quota',()=>{beforeEach(()=>{delete process.env.YOUTUBE_API_KEY;process.env.YOUTUBE_OAUTH_CLIENT_ID='test-client';process.env.YOUTUBE_OAUTH_CLIENT_SECRET='test-secret';process.env.YOUTUBE_OAUTH_REFRESH_TOKEN='test-refresh';process.env.YOUTUBE_CHANNEL_ID='UCtest';__resetYouTubeLiveCache()});afterEach(()=>{if(original.key===undefined)delete process.env.YOUTUBE_API_KEY;else process.env.YOUTUBE_API_KEY=original.key;if(original.channel===undefined)delete process.env.YOUTUBE_CHANNEL_ID;else process.env.YOUTUBE_CHANNEL_ID=original.channel;for(const [name,value] of [['YOUTUBE_OAUTH_CLIENT_ID',original.clientId],['YOUTUBE_OAUTH_CLIENT_SECRET',original.clientSecret],['YOUTUBE_OAUTH_REFRESH_TOKEN',original.refreshToken]] as const){if(value===undefined)delete process.env[name];else process.env[name]=value}})
it('uses 30 min for offline and cache suppresses repeated calls',async()=>{let calls=0;const fetchImpl=async(input:RequestInfo|URL)=>{if(!String(input).includes('oauth2.googleapis.com/token'))calls++;return response([])};const now=new Date('2026-01-01T00:00:00Z');await expect(detectYouTubeLive({now,fetchImpl})).resolves.toBeNull();await expect(detectYouTubeLive({now:new Date(now.getTime()+60_000),fetchImpl})).resolves.toBeNull();expect(calls).toBe(2);expect(revalidationSeconds({status:'OFFLINE'},now)).toBe(1800)})
it('increases upcoming frequency as the event approaches',()=>{const now=new Date('2026-01-01T00:00:00Z');expect(revalidationSeconds({status:'UPCOMING',title:'x',scheduledAt:'2026-01-01T05:00:00Z'},now)).toBe(900);expect(revalidationSeconds({status:'UPCOMING',title:'x',scheduledAt:'2026-01-01T00:45:00Z'},now)).toBe(180);expect(revalidationSeconds({status:'UPCOMING',title:'x',scheduledAt:'2026-01-01T00:10:00Z'},now)).toBe(60)})
it('uses one live search call and detects live',async()=>{let calls=0;let liveSearch='';const fetchImpl=async(input:RequestInfo|URL)=>{const url=String(input);if(!url.includes('oauth2.googleapis.com/token')){calls++;if(url.includes('eventType=live'))liveSearch=url}return response([{id:{videoId:'abc12345678'},snippet:{title:'Culte',liveBroadcastContent:'live'},liveStreamingDetails:{actualStartTime:'2026-01-01T00:00:00Z'}}])};const state=await detectYouTubeLive({now:new Date('2026-01-01T00:01:00Z'),fetchImpl});expect(state?.status).toBe('LIVE');expect(calls).toBe(1);expect(liveSearch).toContain('eventType=live');expect(revalidationSeconds(state!,new Date())).toBe(60)})
it('discovers a scheduled upcoming broadcast outside the latest five videos',async()=>{const urls:string[]=[];const fetchImpl=async(input:RequestInfo|URL)=>{const url=String(input);if(!url.includes('oauth2.googleapis.com/token'))urls.push(url);if(url.includes('eventType=upcoming'))return response([{id:{videoId:'upcoming12345'},snippet:{title:'Demain',liveBroadcastContent:'upcoming',scheduledStartTime:'2026-01-01T05:00:00Z'}}]);return response(Array.from({length:5},(_,index)=>({id:{videoId:`ended${index}123456`},snippet:{title:`Termine ${index}`,liveBroadcastContent:'none'}})))};const state=await detectYouTubeLive({now:new Date('2026-01-01T00:00:00Z'),fetchImpl});expect(state).toMatchObject({status:'UPCOMING',title:'Demain'});expect(urls.some(url=>url.includes('eventType=upcoming'))).toBe(true)})
it('detects upcoming and fails safely on API errors',async()=>{const state=await detectYouTubeLive({now:new Date('2026-01-01T00:00:00Z'),fetchImpl:async()=>response([{id:{videoId:'abc12345678'},snippet:{title:'Demain',liveBroadcastContent:'upcoming',scheduledStartTime:'2026-01-01T05:00:00Z'}}])});expect(state?.status).toBe('UPCOMING');__resetYouTubeLiveCache();await expect(detectYouTubeLive({fetchImpl:async()=>new Response('',{status:503})})).resolves.toBeNull()})
it('tracks a known upcoming video with videos.list after discovery expires',async()=>{const calls:string[]=[];const fetchImpl=async(input:RequestInfo|URL)=>{const url=String(input);if(!url.includes('oauth2.googleapis.com/token'))calls.push(url);if(url.includes('/search?'))return response([{id:{videoId:'abc12345678'},snippet:{title:'Demain',liveBroadcastContent:'upcoming',scheduledStartTime:'2026-01-01T05:00:00Z'}}]);return response([{id:'abc12345678',snippet:{title:'Demain',liveBroadcastContent:'upcoming',scheduledStartTime:'2026-01-01T05:00:00Z'}}])};const now=new Date('2026-01-01T00:00:00Z');await expect(detectYouTubeLive({now,fetchImpl})).resolves.toMatchObject({status:'UPCOMING'});await expect(detectYouTubeLive({now:new Date(now.getTime()+15*60_000+1),fetchImpl})).resolves.toMatchObject({status:'UPCOMING'});expect(calls).toHaveLength(3);expect(calls[2]).toContain('/videos?')})
it('tracks a known live video with videos.list at the 60 second cadence',async()=>{let calls=0;const authHeaders:string[]=[];const fetchImpl=async(input:RequestInfo|URL,init?:RequestInit)=>{if(!String(input).includes('oauth2.googleapis.com/token')){calls++;authHeaders.push(String((init?.headers as Record<string,string>|undefined)?.Authorization||''))};if(String(input).includes('/search?'))return response([{id:{videoId:'abc12345678'},snippet:{title:'Culte',liveBroadcastContent:'live'},liveStreamingDetails:{actualStartTime:'2026-01-01T00:00:00Z'}}]);return response([{id:'abc12345678',snippet:{title:'Culte',liveBroadcastContent:'live'},liveStreamingDetails:{actualStartTime:'2026-01-01T00:00:00Z'}}])};const now=new Date('2026-01-01T00:00:00Z');await expect(detectYouTubeLive({now,fetchImpl})).resolves.toMatchObject({status:'LIVE'});await expect(detectYouTubeLive({now:new Date(now.getTime()+60_001),fetchImpl})).resolves.toMatchObject({status:'LIVE'});expect(calls).toBe(2);expect(authHeaders).toEqual(['Bearer access-test','Bearer access-test']);expect(revalidationSeconds({status:'LIVE',title:'Culte',watchUrl:'/live'},now)).toBe(60)})
it('does not classify ended videos as live',async()=>{const fetchImpl=async(input:RequestInfo|URL)=>{const url=String(input);if(url.includes('eventType=live'))return response([{id:{videoId:'ended1234567'},snippet:{title:'Termine',liveBroadcastContent:'none'}}]);return response([])};await expect(detectYouTubeLive({now:new Date('2026-01-01T00:00:00Z'),fetchImpl})).resolves.toBeNull()})
it('does not expose OAuth credentials on YouTube API requests',async()=>{const requests:{url:string;authorization:string}[]=[];const fetchImpl=async(input:RequestInfo|URL,init?:RequestInit)=>{const url=String(input);if(!url.includes('oauth2.googleapis.com/token'))requests.push({url,authorization:String((init?.headers as Record<string,string>|undefined)?.Authorization||'')});return response([])};await detectYouTubeLive({fetchImpl});expect(requests.every(({url,authorization})=>!url.includes('test-secret')&&!url.includes('test-refresh')&&!authorization.includes('test-secret')&&!authorization.includes('test-refresh'))).toBe(true)})
it('leaves CMS as the safe fallback when YouTube is unavailable',async()=>{__resetYouTubeLiveCache();const detected=await detectYouTubeLive({fetchImpl:async()=>new Response('',{status:503})});expect(detected).toBeNull();expect(resolveLiveState([{status:'live',title:'Culte CMS',youtube_url:'https://youtu.be/abcdefghijk'}])).toMatchObject({status:'LIVE',title:'Culte CMS'});expect(resolveLiveState([])).toEqual({status:'OFFLINE'})})
it('fails safely when OAuth configuration is incomplete',async()=>{process.env.YOUTUBE_API_KEY='legacy-test';delete process.env.YOUTUBE_OAUTH_REFRESH_TOKEN;__resetYouTubeLiveCache();await expect(detectYouTubeLive({fetchImpl:async()=>response([{id:{videoId:'abc12345678'},snippet:{title:'Culte',liveBroadcastContent:'live'}}])})).resolves.toBeNull();expect(resolveLiveState([])).toEqual({status:'OFFLINE'})})
})
